version: '3.7'
services: 
  nginx: 
    image: nginx:1.17.6
    container_name: nginx 
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/:/etc/nginx/conf.d
      - ./html/:/usr/share/nginx/html
      - ./logs/:/var/log/nginx
    ports: 
      - "80:80"


    
