version: '3.7'
services: 
  redis: 
    image: redis:5.0.7
    container_name: redis 
    command: ["redis-server", "/etc/redis.conf"]
    volumes: 
      - /data/redisdata:/data
      - ./redis.conf:/etc/redis.conf
    ports: 
      - "6379:6379"


    
